server.port=8080
spring.application.name=climalert-service
spring.threads.virtual.enabled=true
weather.api.url=https://api.weatherapi.com/v1/current.json
weather.api.key=4eebe22325f4473db8f23613260307
weather.api.location=CABA