server.port=8080
spring.application.name=climalert-service
spring.threads.virtual.enabled=true
weather.api.url=https://api.weatherapi.com/v1/current.json
weather.api.key=4eebe22325f4473db8f23613260307
weather.api.location=CABA
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=86420275865322
spring.mail.password=31bcf703d75de0
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
alert.mail.recipients=admin@clima.com,emergencias@clima.com,meteorologia@clima.com